name: Continuos Delivery

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Get Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REPOSITORY_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            luisfalconmx/portfolio:latest
            luisfalconmx/portfolio:${{ env.RELEASE_VERSION }}
            ghcr.io/luisfalconmx/portfolio:latest
            ghcr.io/luisfalconmx/portfolio:${{ env.RELEASE_VERSION }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
        with:
          destination_container_repo: luisfalconmx/portfolio
          provider: dockerhub
          short_description: ${{ secrets.DOCKERHUB_DESCRIPTION }}
          readme_file: 'README.md'
